0 ->VARIABLE SUM
\ : UD. ( ud -- ) <# #S #> TYPE ; 		\ type unsigned double 

: FIB ( u1 u2 -- u2 u1+u2 )	DUP ROT + ; \ generate Fibonacci

: MAIN BEGIN .S
	DUP 2 MOD IF ELSE ROT OVER + ROT ROT THEN 	\ if even then sum
	FIB DUP 4000000 > 					\ is < 4e6 ?
CR UNTIL ; 

0 1 2 MAIN 2DROP .
\ SUM ?

\EOF
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence 
whose values do not exceed four million, 
find the sum of the even-valued terms.

Каждый новый член в последовательности Фибоначчи 
генерируется путем добавления двух предыдущих членов. 
Начиная с 1 и 2, первые 10 терминов будут:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Рассмотрев члены последовательности Фибоначчи, 
значения которых не превышают четырех миллионов, 
найдите сумму четных членов.
