: DIVS ( num -- #divs )  \ count divisors
	0 SWAP DUP 1+ 1 DO DUP I MOD IF ELSE >R 1+ R> THEN LOOP
	DROP ;
: BRUT ( #divs -- value ) \ generate tri nums
	1 1 BEGIN
		>R 1+ R> OVER +
		DUP DIVS DUP 300 > IF .S CR THEN 3 PICK >
	UNTIL NIP NIP ;
500 BRUT . 

\EOF 76576500

1 1
2 3
3 6
4 10
5 15
6 21
7 28

Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

Проблема 12
Последовательность треугольных чисел создается сложением натуральных чисел.
Таким образом, 7-е число треугольника будет 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
Первые десять терминов будут такими:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Перечислим множители первых семи чисел треугольника:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
Мы видим, что 28 - это первое число в треугольнике, у которого больше пяти делителей.
Какое значение имеет первое число треугольника, которое имеет более пятисот делителей?