: PEN@  ( i -- u )   DUP 3 * 1 - UM* 1 2 M*/ D>S ;
: HEX@  ( i -- u )   DUP 2 * 1- * ;
: BRUT  ( i -- u )   >R
   BEGIN 1+ DUP 
      HEX@   R>
      BEGIN 1+ DUP  PEN@ 
         2 PICK < INVERT
      UNTIL DUP 1- >R
      PEN@
      = IF  HEX@ R> DROP EXIT  THEN
   AGAIN ;
143 165  BRUT .

\EOF 1533776805
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
