: U>PAD  ( u shift -- len )   0 ROT
   BEGIN  10 /MOD 2DUP OR
   WHILE  SWAP 2OVER PAD + + C! SWAP 1+ SWAP
   REPEAT 2DROP NIP ;
: A^B  ( a b -- len )   SWAP DUP 0 U>PAD ROT
   1 DO SWAP OVER
      0 SWAP 0
      DO OVER
         PAD I + C@ * 10 /MOD
         SWAP ROT +
         10 /MOD ROT +
         SWAP PAD I + C!
      LOOP
      2 PICK U>PAD ROT +
   LOOP NIP ;
: %SEEK  ( # adr len -- #' adr' len | 0 )
   ROT DUP
   IF 1- ROT
      DUP C@ 3 PICK =
      IF DUP 1+ 3 PICK PAD OVER COMPARE
         IF DUP C@ 1+ + ROT RECURSE
         ELSE 2DROP 2DROP 0
         THEN
      ELSE DUP C@ 1+ + ROT RECURSE
      THEN
   ELSE ROT ROT
   THEN  ;
: BRUT  ( border -- terms )  1+
   1000000 ALLOCATE ABORT" Not enough mem "
   DUP 1 SWAP C! DUP 1+ 4 SWAP C!
   1 SWAP
   2 PICK 2 DO
      2 PICK 2 DO
         J I A^B
         2DUP 4 PICK ROT ROT %SEEK
         IF NIP 2DUP 2>R C!
            2R> 1+ PAD SWAP ROT CMOVE
            SWAP 1+ SWAP
         THEN
      LOOP
   LOOP DROP NIP ;
100 BRUT .

\EOF 9183
Problem 29
Distinct powers
Consider all integer combinations of ab for 2 <= a <= 5 and 2 <= b <= 5:
    2^2=4, 2^3=8, 2^4=16, 2^5=32
    3^2=9, 3^3=27, 3^4=81, 3^5=243
    4^2=16, 4^3=64, 4^4=256, 4^5=1024
    5^2=25, 5^3=125, 5^4=625, 5^5=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
